#lang racket
(require racket/struct)
(require "defs.rkt")
(require "examples.rkt")
(require "my-interpreter.rkt")
(require "model-interpreter.rkt")
;---------------------------------------------------------

(displayln  "\nProgram 13********************************\n")

(displayln prog13)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog13)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog13)
(displayln "Printing difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)

(displayln  "\nProgram 12********************************\n")
(displayln prog12)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog12)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog12)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)

(displayln  "\nProgram 11********************************\n")
(displayln prog11)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog11)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog11)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)


;(displayln  "\nProgram 10********************************\n")
;;This program should give an error.
;(displayln prog10)
;(displayln "\nEvaluation using your interpreter***********\n")
;(eval-program prog10)
;(displayln "\nEvaluation using model interpreter ************\n")
;(model-eval-program prog10)
;(displayln "\nPrinting difference: #t means no difference\n")
;(equal? stacks model-stacks)
;(model-cleanup)
;(cleanup)

(displayln  "\nProgram 9********************************\n")
(displayln prog9)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog9)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog9)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)

(displayln  "\nProgram 8********************************\n")
(displayln prog8)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog8)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog8)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)

(displayln  "\nProgram 7********************************\n")
(displayln prog7)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog7)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog7)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)


(displayln  "\nProgram 6********************************\n")
(displayln prog6)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog6)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog6)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)

(displayln  "\nProgram 5********************************\n")
(displayln prog5)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog5)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog5)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)

;(displayln  "\nProgram 4********************************\n")
;This program should give an error
;(displayln prog4)
;(displayln "\nEvaluation using your interpreter***********\n")
;(eval-program prog4)
;(displayln "\nEvaluation using model interpreter ************\n")
;(model-eval-program prog4)
;(displayln "\nPrinting difference: #t means no difference\n")
;(equal? stacks model-stacks)
;(model-cleanup)
;(cleanup)

(displayln  "\nProgram 3********************************\n")
(displayln prog3)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog3)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog3)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)


(displayln  "\nProgram 2********************************\n")
(displayln prog2)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog2)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog2)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)


(displayln  "\nProgram 1********************************\n")
(displayln prog1)
(displayln "\nEvaluation using your interpreter***********\n")
(eval-program prog1)
(displayln "\nEvaluation using model interpreter ************\n")
(model-eval-program prog1)
(displayln "\nPrinting difference: #t means no difference\n")
(equal? stacks model-stacks)
(model-cleanup)
(cleanup)
